name:                ecash
version:             0.1.0.0
github:              "kurtostfeld/LearningElectronicCash"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kurtostfeld/LearningElectronicCash#readme>

dependencies:
- base >= 4.7 && < 5

# stack ghci ecash:lib
library:
  source-dirs: src
  dependencies:
    - containers
    - multimap
    - random
    - split

executables:
  # stack ghci ecash:exe:paydemo-exe
  # stack exec paydemo-exe
  paydemo-exe:
    main:                Main.hs
    source-dirs:         paydemo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ecash

  # stack exec doubledeposit-exe
  doubledeposit-exe:
    main:                Main.hs
    source-dirs:         doubledeposit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ecash

  # stack exec doublepayment-exe
  doublepayment-exe:
    main:                Main.hs
    source-dirs:         doublepayment
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ecash
    
tests:
  # stack test
  ecash-test:
    main:                m343lTests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ecash
    - HUnit
    - test-framework
    - test-framework-hunit
